site_name: NeuraFlash Chatbot Solution Documentation
theme: 'material'
pages: 
  - Home: index.md
  - About Me: about.md
  - Admin Guide: admin_guide.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  
