site_name: NeuraFlash Chatbot Solution Documentation
theme: 'material'
pages: 
  - Home: index.md
  - About Me: about.md
  - Admin Guide portal: admin_guide_portal.md
  - Admin Guide community: admin_guide_community.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md

  
